services:
  - type: web
    name: yanc-website
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    # Add allowed hosts to prevent Vite errors
    routes:
      - type: rewrite
        source: /*
        destination: /